v1.0.0  Juniper compatibility, Py3, other fixes
appsembler/xblock-video pull request #38
Opened 2021-08-05 00:23 UTC by bryanlandia

## Change description

v1.0.0 release.  New major release since it now requires Python 3. 
* Juniper compatibliity
* BrightCove style fixes for Video.js v7-based player compatibility
* fixes setting account_id from settings
* accessibility fix (title property on iframe)
* Brightcove width property fix
* Chrome mute on autoplay

## Type of change
- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

> Fix [#1]() 

## Checklists

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

2021-08-05 02:54 UTC, bryanlandia commented
@thraxil I added you as reviewer and feel free if you want, but I need to get @abeals to add some more team members on this repo!

2021-08-05 08:27 UTC, thraxil requested changes
@bryanlandia can we split this into mulitple single-purpose PRs? This is way to much to review in one giant chunk.

2021-08-05 18:16 UTC, bryanlandia commented
Thanks for taking a look @thraxil.  Sure, I'll split it  up.  Two of them will still be quite large, one is basically just bringing in a lot of changes from Raccoon Gang's fork, another a slew of Py3 changes, and then there are a few other fixes.  I'll keep this PR for the version bump then.

2021-08-09 08:33 UTC, thraxil approved these changes

2021-08-09 15:12 UTC, merged